### ISSUE TITLE
fopen errors are suppressed

### ISSUE THREAD

**Issue by plaffitt** [biigle/laravel-file-cache#6]
Hello,

First I would like to say that I very much appreciate your work, it's fantastic and very useful to us. However, I'm annoyed by the fact that fopen errors are suppressed (in v2.2.6, we're using Laravel 5.8). Indeed I had to enable debugging in production and place some calls to `dd` (again, in **production**..) to find out that fopen was (or would be) throwing an exception stating that:

> Error while caching file 'https://........': fopen(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0

This issue could have been resolved quite easily if those errors hadn't be suppressed, and I think they should not be.

I look forward to hearing from you, thanks.

**Comment by mzur** [comment]
As far as I know `fopen` will raise a warning which can't be caught in case of an error. I'd rather make it throw an exception which can be handled by user code. Maybe this can be done with a custom temporary error handler. There is also a case where `fopen` may [intentionally](https://github.com/biigle/laravel-file-cache/blob/f5bf8ad2b66d84ec1edf07934a53c4e3f1251bc4/src/FileCache.php#L362) fail if a file exists. In this case warnings could be conditionally converted to exceptions by examining the warning message. What do you think?

**Comment by mzur** [comment]
Please reopen if this is still relevant.

**Comment by plaffitt** [comment]
Sorry I missed your first answer. I think it's still relevant and converting warnings to Exceptions could be a good solution since it makes users able to handle them.

**Comment by mzur** [comment]
Would you be willing to send a pull request with a proposed solution?

**Comment by plaffitt** [comment]
I'm quite busy currently, but I can give it a try in September.

**Comment by stevebauman** [comment]
Might be worth just using the PHP [Safe](https://github.com/thecodingmachine/safe) library so exceptions are raised without having to implement custom error handling logic:

```php
use function Safe\fopen;

// ...

$handle = fopen($cachedPath, 'x+');
```

**Comment by mzur** [comment]
#14 implements use of Guzzle instead of `fopen` for HTTP requests. While warnings are still suppressed for local files, your immediate issue would no longer occur. Please reopen if there is still something to discuss.
