### ISSUE TITLE
cant be installed in latest versions of laravel

### ISSUE THREAD

**Issue by Ham3D** [biigle/laravel-file-cache#7]
its installs and works in version 6.x
but in later versions, there is a conflict that prevents it from installing

![Screen Shot 2021-06-17 at 10 56 33](https://user-images.githubusercontent.com/3233668/122343199-afe5a080-cf5a-11eb-8208-dcf5929e9b6b.png)

**Comment by mzur** [comment]
This should be possible now.

**Comment by Ham3D** [comment]
still not installable in fresh Laravel 8.50, php 7.4, 8.0

![Screen Shot 2021-07-14 at 19 43 16](https://user-images.githubusercontent.com/3233668/125646697-d6605d5e-975e-4b8c-89cd-130e939254a0.png)

and not installable in fresh lumen 8.2.4, php 7.4 and php 8.0
![Screen Shot 2021-07-14 at 19 46 35](https://user-images.githubusercontent.com/3233668/125647150-a9a73136-1361-4217-a46a-0703dda6742f.png)

**Comment by mzur** [comment]
Sorry, forgot to create a new release. Please retry.
