### ISSUE TITLE
is there a way to stream content

### ISSUE THREAD

**Issue by Ham3D** [biigle/laravel-file-cache#9]
is there a way to stream content while they are caching ?

**Comment by mzur** [comment]
Depends on what you mean. There is the `getStream` method. It will read a stream from the cache if the file is already cached. It will also read a stream directly from the source if the file is not cached. But it will not stream a file from the source and put it in the cache at the same time.

**Comment by Ham3D** [comment]
imagine we have a 1gb file, it needs 10seconds to download on server, is there any way to start streaming it to user while we are caching it?

**Comment by mzur** [comment]
You could use `getStream` and in parallel launch a queue job that just calls `get` to cache the file for subsequent calls. However, this fetches the file twice. If you want something more sophisticated you'd have to implement it yourself.
